#version 460
#pragma shader_stage(compute)

#include "Agx.glsl"

layout(local_size_x = 8, local_size_y = 8) in;

layout(binding = 0, rgba32f) readonly uniform image2D inputImage;
layout(binding = 1, rgba8) writeonly uniform image2D outputImage;

void main() {
    vec4 hdrImage = imageLoad(inputImage, ivec2(gl_GlobalInvocationID.xy));
    imageStore(outputImage, ivec2(gl_GlobalInvocationID.xy), vec4(agx(hdrImage.rgb), hdrImage.a));
}