#include "Realtime/FfxPlatform.h"

#include <array>
#include <deque>
#include <mutex>
#include <string>
#include <vector>

#include <FidelityFX/host/ffx_fsr3upscaler.h>
#include <FidelityFX/host/backends/vk/ffx_vk.h>
#include <ffx_shader_blobs.h>
#include <fsr3upscaler/ffx_fsr3upscaler_private.h>
#include <spirv_reflect.h>

// Shader lookup for the FidelityFX Vulkan backend.
//
// The SDK normally ships these as headers generated by its Windows-only
// shader compiler: SPIR-V for every permutation plus binding tables. NoorRay
// instead compiles the FSR upscaler's GLSL passes with glslang at build time,
// for the one permutation its context flags select, and reads the binding
// tables from the SPIR-V with SPIRV-Reflect exactly as that compiler does.

namespace
{
// The permutation compiled by CMakeLists.txt (NR_FSR_SHADER_DEFINES). The
// component derives these bits from the context flags FsrUpscaler uses.
constexpr std::uint32_t RequiredPermutation =
    FSR3UPSCALER_SHADER_PERMUTATION_HDR_COLOR_INPUT
    | FSR3UPSCALER_SHADER_PERMUTATION_LOW_RES_MOTION_VECTORS
    | FSR3UPSCALER_SHADER_PERMUTATION_DEPTH_INVERTED;
// Bits that only select optimizations: LUT-based Lanczos, 16-bit math and
// wide SIMD lanes. The compiled reference variants are used for all of them.
constexpr std::uint32_t IgnoredPermutation =
    FSR3UPSCALER_SHADER_PERMUTATION_USE_LANCZOS_TYPE
    | FSR3UPSCALER_SHADER_PERMUTATION_ALLOW_FP16
    | FSR3UPSCALER_SHADER_PERMUTATION_FORCE_WAVE64;

alignas(std::uint32_t) constexpr unsigned char prepareInputsSpv[] = {
    #embed "Fsr/ffx_fsr3upscaler_prepare_inputs_pass.spv"
};
alignas(std::uint32_t) constexpr unsigned char lumaPyramidSpv[] = {
    #embed "Fsr/ffx_fsr3upscaler_luma_pyramid_pass.spv"
};
alignas(std::uint32_t) constexpr unsigned char shadingChangePyramidSpv[] = {
    #embed "Fsr/ffx_fsr3upscaler_shading_change_pyramid_pass.spv"
};
alignas(std::uint32_t) constexpr unsigned char shadingChangeSpv[] = {
    #embed "Fsr/ffx_fsr3upscaler_shading_change_pass.spv"
};
alignas(std::uint32_t) constexpr unsigned char prepareReactivitySpv[] = {
    #embed "Fsr/ffx_fsr3upscaler_prepare_reactivity_pass.spv"
};
alignas(std::uint32_t) constexpr unsigned char lumaInstabilitySpv[] = {
    #embed "Fsr/ffx_fsr3upscaler_luma_instability_pass.spv"
};
alignas(std::uint32_t) constexpr unsigned char accumulateSpv[] = {
    #embed "Fsr/ffx_fsr3upscaler_accumulate_pass.spv"
};
alignas(std::uint32_t) constexpr unsigned char accumulateSharpenSpv[] = {
    #embed "Fsr/ffx_fsr3upscaler_accumulate_pass_sharpen.spv"
};
alignas(std::uint32_t) constexpr unsigned char rcasSpv[] = {
    #embed "Fsr/ffx_fsr3upscaler_rcas_pass.spv"
};
alignas(std::uint32_t) constexpr unsigned char debugViewSpv[] = {
    #embed "Fsr/ffx_fsr3upscaler_debug_view_pass.spv"
};
alignas(std::uint32_t) constexpr unsigned char autogenReactiveSpv[] = {
    #embed "Fsr/ffx_fsr3upscaler_autogen_reactive_pass.spv"
};

struct Category
{
    std::vector<std::string> names;
    std::vector<const char*> namePointers;
    std::vector<std::uint32_t> bindings;
    std::vector<std::uint32_t> counts;
    std::vector<std::uint32_t> spaces;

    void add(const SpvReflectDescriptorBinding& binding, const std::uint32_t set)
    {
        names.emplace_back(binding.name ? binding.name : "");
        bindings.push_back(binding.binding);
        counts.push_back(binding.count);
        spaces.push_back(set);
    }

    void finish()
    {
        namePointers.clear();
        for (const std::string& name : names)
            namePointers.push_back(name.c_str());
    }

    std::uint32_t size() const { return static_cast<std::uint32_t>(bindings.size()); }
};

struct ReflectedShader
{
    const unsigned char* bytes{};
    std::size_t size{};
    Category constantBuffers;
    Category srvTextures;
    Category uavTextures;
    Category srvBuffers;
    Category uavBuffers;
    Category samplers;
    Category accelerationStructures;
};

bool reflect(ReflectedShader& shader)
{
    SpvReflectShaderModule module{};
    if (spvReflectCreateShaderModule(shader.size, shader.bytes, &module) != SPV_REFLECT_RESULT_SUCCESS)
        return false;
    std::uint32_t setCount = 0;
    spvReflectEnumerateDescriptorSets(&module, &setCount, nullptr);
    std::vector<SpvReflectDescriptorSet*> sets(setCount);
    spvReflectEnumerateDescriptorSets(&module, &setCount, sets.data());
    bool supported = true;
    for (const SpvReflectDescriptorSet* set : sets) {
        for (std::uint32_t i = 0; i < set->binding_count; ++i) {
            const SpvReflectDescriptorBinding& binding = *set->bindings[i];
            switch (binding.descriptor_type) {
            case SPV_REFLECT_DESCRIPTOR_TYPE_UNIFORM_BUFFER:
                shader.constantBuffers.add(binding, set->set);
                break;
            case SPV_REFLECT_DESCRIPTOR_TYPE_SAMPLED_IMAGE:
                shader.srvTextures.add(binding, set->set);
                break;
            case SPV_REFLECT_DESCRIPTOR_TYPE_SAMPLER:
                shader.samplers.add(binding, set->set);
                break;
            case SPV_REFLECT_DESCRIPTOR_TYPE_STORAGE_IMAGE:
                shader.uavTextures.add(binding, set->set);
                break;
            case SPV_REFLECT_DESCRIPTOR_TYPE_STORAGE_BUFFER:
                if (binding.resource_type == SPV_REFLECT_RESOURCE_FLAG_SRV)
                    shader.srvBuffers.add(binding, set->set);
                else
                    shader.uavBuffers.add(binding, set->set);
                break;
            case SPV_REFLECT_DESCRIPTOR_TYPE_ACCELERATION_STRUCTURE_KHR:
                shader.accelerationStructures.add(binding, set->set);
                break;
            default:
                supported = false;
                break;
            }
        }
    }
    spvReflectDestroyShaderModule(&module);
    for (Category* category : {&shader.constantBuffers, &shader.srvTextures,
             &shader.uavTextures, &shader.srvBuffers, &shader.uavBuffers,
             &shader.samplers, &shader.accelerationStructures})
        category->finish();
    return supported;
}

struct ShaderSource
{
    const unsigned char* bytes;
    std::size_t size;
};

bool source(const FfxFsr3UpscalerPass pass, const std::uint32_t permutation, ShaderSource& out)
{
    switch (pass) {
    case FFX_FSR3UPSCALER_PASS_PREPARE_INPUTS: out = {prepareInputsSpv, sizeof(prepareInputsSpv)}; return true;
    case FFX_FSR3UPSCALER_PASS_LUMA_PYRAMID: out = {lumaPyramidSpv, sizeof(lumaPyramidSpv)}; return true;
    case FFX_FSR3UPSCALER_PASS_SHADING_CHANGE_PYRAMID:
        out = {shadingChangePyramidSpv, sizeof(shadingChangePyramidSpv)};
        return true;
    case FFX_FSR3UPSCALER_PASS_SHADING_CHANGE: out = {shadingChangeSpv, sizeof(shadingChangeSpv)}; return true;
    case FFX_FSR3UPSCALER_PASS_PREPARE_REACTIVITY:
        out = {prepareReactivitySpv, sizeof(prepareReactivitySpv)};
        return true;
    case FFX_FSR3UPSCALER_PASS_LUMA_INSTABILITY:
        out = {lumaInstabilitySpv, sizeof(lumaInstabilitySpv)};
        return true;
    case FFX_FSR3UPSCALER_PASS_ACCUMULATE:
    case FFX_FSR3UPSCALER_PASS_ACCUMULATE_SHARPEN:
        if ((permutation & FSR3UPSCALER_SHADER_PERMUTATION_ENABLE_SHARPENING) != 0)
            out = {accumulateSharpenSpv, sizeof(accumulateSharpenSpv)};
        else
            out = {accumulateSpv, sizeof(accumulateSpv)};
        return true;
    case FFX_FSR3UPSCALER_PASS_RCAS: out = {rcasSpv, sizeof(rcasSpv)}; return true;
    case FFX_FSR3UPSCALER_PASS_DEBUG_VIEW: out = {debugViewSpv, sizeof(debugViewSpv)}; return true;
    case FFX_FSR3UPSCALER_PASS_GENERATE_REACTIVE:
        out = {autogenReactiveSpv, sizeof(autogenReactiveSpv)};
        return true;
    default:
        return false;
    }
}

std::mutex reflectedMutex;
// Blobs point into these entries, so they must never move.
std::deque<ReflectedShader> reflectedShaders;

// Mutable because the SDK's blob stores its name tables as const char**.
ReflectedShader* reflected(const ShaderSource& shaderSource)
{
    const std::lock_guard lock(reflectedMutex);
    for (ReflectedShader& shader : reflectedShaders)
        if (shader.bytes == shaderSource.bytes)
            return &shader;
    ReflectedShader& shader = reflectedShaders.emplace_back();
    shader.bytes = shaderSource.bytes;
    shader.size = shaderSource.size;
    if (!reflect(shader)) {
        reflectedShaders.pop_back();
        return nullptr;
    }
    return &shader;
}
}

FfxErrorCode ffxGetPermutationBlobByIndex(const FfxEffect effectId, const FfxPass passId,
    const FfxBindStage, const uint32_t permutationOptions, FfxShaderBlob* outBlob)
{
    if (!outBlob)
        return FFX_ERROR_INVALID_POINTER;
    if (effectId != FFX_EFFECT_FSR3UPSCALER)
        return FFX_ERROR_INVALID_ENUM;
    const std::uint32_t permutation = permutationOptions & ~IgnoredPermutation
        & ~FSR3UPSCALER_SHADER_PERMUTATION_ENABLE_SHARPENING;
    if (permutation != RequiredPermutation) {
        std::fprintf(stderr, "[FSR] no compiled shader permutation for options 0x%x\n",
            permutationOptions);
        return FFX_ERROR_INVALID_ARGUMENT;
    }
    ShaderSource shaderSource{};
    if (!source(static_cast<FfxFsr3UpscalerPass>(passId), permutationOptions, shaderSource))
        return FFX_ERROR_INVALID_ENUM;
    ReflectedShader* shader = reflected(shaderSource);
    if (!shader)
        return FFX_ERROR_BACKEND_API_ERROR;

    const FfxShaderBlob blob = {
        shader->bytes, static_cast<uint32_t>(shader->size),
        shader->constantBuffers.size(), shader->srvTextures.size(), shader->uavTextures.size(),
        shader->srvBuffers.size(), shader->uavBuffers.size(), shader->samplers.size(),
        shader->accelerationStructures.size(),
        shader->constantBuffers.namePointers.data(), shader->constantBuffers.bindings.data(),
        shader->constantBuffers.counts.data(), shader->constantBuffers.spaces.data(),
        shader->srvTextures.namePointers.data(), shader->srvTextures.bindings.data(),
        shader->srvTextures.counts.data(), shader->srvTextures.spaces.data(),
        shader->uavTextures.namePointers.data(), shader->uavTextures.bindings.data(),
        shader->uavTextures.counts.data(), shader->uavTextures.spaces.data(),
        shader->srvBuffers.namePointers.data(), shader->srvBuffers.bindings.data(),
        shader->srvBuffers.counts.data(), shader->srvBuffers.spaces.data(),
        shader->uavBuffers.namePointers.data(), shader->uavBuffers.bindings.data(),
        shader->uavBuffers.counts.data(), shader->uavBuffers.spaces.data(),
        shader->samplers.namePointers.data(), shader->samplers.bindings.data(),
        shader->samplers.counts.data(), shader->samplers.spaces.data(),
        shader->accelerationStructures.namePointers.data(),
        shader->accelerationStructures.bindings.data(),
        shader->accelerationStructures.counts.data(),
        shader->accelerationStructures.spaces.data(),
    };
    // FfxShaderBlob has const members, so it is copied rather than assigned.
    std::memcpy(static_cast<void*>(outBlob), &blob, sizeof(blob));
    return FFX_OK;
}

FfxErrorCode ffxIsWave64(FfxEffect, uint32_t, bool& isWave64)
{
    isWave64 = false;
    return FFX_OK;
}

// Frame generation replaces the swapchain; NoorRay only upscales, and the
// SDK's swapchain implementation is Windows-only.
FfxErrorCode ffxSetFrameGenerationConfigToSwapchainVK(FfxFrameGenerationConfig const*)
{
    return FFX_ERROR_INVALID_ARGUMENT;
}
