name: Release Builder (macOS)

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: macos-15

    steps:
      - name: Change XCode Version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest
    
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Cache CMake Files
        uses: actions/cache@v4
        with:
          path: |
            build/CMakeCache.txt
            build/CMakeFiles
          key: cmake-${{ runner.os }}-${{ hashFiles('CMakeLists.txt') }}

      - name: Set Xcode 16.4 (with macOS 15.5 SDK)
        run: |
          echo "Using Xcode version:"
          xcodebuild -version
          export MACOSX_DEPLOYMENT_TARGET=15.5
          export SDKROOT=$(xcodebuild -sdk macosx15.5 -version Path)
          echo "SDKROOT is set to $SDKROOT"
        shell: bash

      - name: Install Vulkan SDK
        uses: jakoch/install-vulkan-sdk-action@v1
        with:
          install_runtime: true
          cache: true
          stripdown: true

      - name: Print full Vulkan SDK folder structure (files + folders)
        run: |
          echo "VULKAN_SDK is at: $VULKAN_SDK"
          find "$VULKAN_SDK"

      - name: Compile shaders
        run: |
          export PATH="$VULKAN_SDK/macOS/bin:$PATH"
          cd src/shaders
          chmod +x recompile.sh
          ./recompile.sh

      - name: Install llvm@20
        run: |
          brew update
          brew install llvm@20

      - name: Configure and Build with llvm@20 Clang
        run: |
          export LLVM_PREFIX=$(brew --prefix llvm@20)
          export MACOSX_DEPLOYMENT_TARGET=15.5
          export SDKROOT=$(xcodebuild -sdk macosx15.5 -version Path)
          cmake -S . -B build -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_CXX_STANDARD=23 \
            -DCMAKE_C_COMPILER=$LLVM_PREFIX/bin/clang \
            -DCMAKE_CXX_COMPILER=$LLVM_PREFIX/bin/clang++ \
            -DCMAKE_C_FLAGS="-std=c2x" \
            -DCMAKE_CXX_FLAGS="-std=c++23" \
            -DCMAKE_OSX_DEPLOYMENT_TARGET=$MACOSX_DEPLOYMENT_TARGET \
            -DCMAKE_OSX_SYSROOT=$SDKROOT

          cmake --build build --config Release

      - name: Upload macOS Application
        uses: actions/upload-artifact@v4
        with:
          name: NoorRay-macOS
          path: build/NoorRay.app
